name: Angular CI

on:
  pull_request:
    branches:
      - develop
      - staging
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:headless

      - name: Build
        run: npm run build:prod
